baseURL = "https://bensiegils.com/"
languageCode = "en-us"
title = "BensiEgils"
theme = "hextra"

# Enable rendering HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/posts"
    weight = 10

# Module configuration
[module]
[[module.imports]]
  path = 'github.com/imfing/hextra'

# Theme parameters
[params]
  description = "Documenting my journey with Azure, PowerShell, automation, and security."
  
  [params.footer]
    enable = true
    
  [params.navbar]
    enable = true
    
  [params.homepage]
    layout = "page" # Valid options: page, custom
    
  [params.search]
    enable = true
    
  [params.themes]
    enable = true
    defaultTheme = "dark"

# Output formats
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

# Suppress specific warnings
[security]
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']