baseURL = "https://lubenz007.github.io/bensiegils/"
languageCode = "en-us"
title = "BensiEgils"
theme = "hextra"

[module]
[[module.imports]]
  path = 'github.com/imfing/hextra'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/posts"
    weight = 10