baseURL = "https://lubenz007.github.io/bensiegils/"
languageCode = "en-us"
title = "BensiEgils"
theme = "hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
[[module.imports]]
  path = 'github.com/imfing/hextra'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/posts"
    weight = 10

# Suppress specific warnings
ignoreErrors = ['error-remote-getjson']
ignoreLogs = ['warning-goldmark-raw-html']