baseURL = "https://lubenz007.github.io/bensiegils/"
languageCode = "en-us"
title = "BensiEgils"
theme = "hextra"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[security.http]
  urls = ['.*']

[module]
[[module.imports]]
  path = 'github.com/imfing/hextra'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/posts"
    weight = 10
      unsafe = true
  [markup.highlight]
    lineNos = true
    noClasses = false
    style = "github"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

[taxonomies]
  category = "categories"
  tag = "tags"

# Table of Contents configuration
[params.toc]
  displayTags = true

[permalinks]
  posts = "/posts/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]