name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.146.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Print Hugo Version
        run: hugo version

      - name: Print Hugo Module Status
        run: hugo mod graph

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Clear Hugo Module Cache
        run: rm -rf ~/.cache/hugo_cache && rm -rf ~/.hugo_cache && rm -rf ./resources

      - name: Download Hugo Modules
        run: hugo mod tidy

      - name: Build with Hugo
        env:
          HUGO_BASEURL: 'https://lubenz007.github.io/bensiegils/'
        run: |
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
